config/routes.rb
Nestedfrom::Application.routes.draw do
resources :pjs
resources :bgs
end

app/models/bg.rb
class Bg < ActiveRecord::Base
	belongs_to :pj
	attr_accessible :bname, :priority, :pj_id
	validates :bname, :priority, :pj_id, :presence => true
end

app/models/pj.rb
class Pj < ActiveRecord::Base
		has_many :bgs
	attr_accessible :pname, :user_id
	validates :pname, :user_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bgs_controller.rb
class BgsController < ApplicationController
	def new
		@pj = Pj.find(params[:id])
		@bg = @pj.bgs.build
	end
	def create
		@pj = Pj.find(params[:id])
		@bg = @pj.bgs.build(params[:bg])
		if @bg.valid?
			@bg.save
			redirect_to new_bg_path(:id => @pj.id)
		else
			redirect_to new_bg_path
		end
	end
  
 def index
    # @users = User.all

  #   	@pj = Pj.find(params[:id])
		# @bg = @pj.bgs.build
   @bg = Bg.all

   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bg }
    end
  end
  
  def show
    @bg = Bg.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bg }
    end
  end
  
  def edit
  # 	@pj = Pj.find(params[:id])
		# @bg = @pj.bgs.find(params[:id])
    
  end
  
  def update
    @bg = Bg.find(params[:id])

    respond_to do |format|
      if @bg.update_attributes(params[:bg])
        format.html { redirect_to bgs_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bg.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy

    # @pj = Pj.find(params[:id])
    # @bg = @pj.bgs.find(params[:id])
    @bg = Bg.destroy(params[:id])
    # @bg.destroy

    respond_to do |format|
      format.html { redirect_to bgs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pjs_controller.rb
class PjsController < ApplicationController
		def new
		@pj = Pj.new
		@pjs = Pj.all
   end
   def create
      @pj = Pj.new(params[:pj])
      if @pj.valid? 
         @pj.save
         redirect_to new_pj_path, notice: "Project #{ @pj.pname } Created Successfully."
      else 
          redirect_to new_pj_path      
      end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bgs_helper.rb
module BgsHelper
end

app/helpers/pjs_helper.rb
module PjsHelper
end

app/views/bgs/_form.html.erb
<div class="alert alert-error">
  <h4 class="pagination-centered">Bugs</h4>
</div>

<%= simple_form_for @bg, :url => { :action => :create, :id => @pj.id }  do |f| %>
<%= f.input :bname, :label => "Name :" %>
<%= f.input :priority, :label => "Priority :"%>
<%= f.button :submit, 'Save', :class => 'btn btn-huge btn-info btn-embossed mlm' %>
<% end %>
<hr />

app/views/bgs/edit.html.erb
<h1>Edit Bugs </h1><br/><br/>

<%= render 'form' %>

<%= link_to 'Show', @bg,:class => "btn btn-mini" %> |
<%= link_to 'Back', bgs_path,:class => "btn btn-mini" %>

app/views/bgs/index.html.erb
<h5>Project Name :<%= @pj.pname %>(<%= link_to "back",new_pj_path %>)</h5> 
<h4 align="center"><caption>List Of Bugs For This Project</caption></h4>
<table class="table table-hover">
       <% if @pj.bgs.exists? %>
    <tr>
    <th>Bug Name</th>
    <th>Priority</th>
    <th>Created On</th>
    <th>Last Update</th>
    <th> </th>
     
  </tr>
<% for item in @pj.bgs %>
<% if !item.name.nil? %>
<tr>
  <td><%= item.bname %></td>
  <td> <%= item.priority %></td>
  <td><%= item.created_at.strftime("%b %d, %Y") %></td>
  <td><%= item.updated_at.strftime("%b %d, %Y") %></td>
  <td><%= link_to 'Show', item %> 
   <%= link_to 'Edit', edit_bg_path(item) %> 
     <%= link_to 'destroy', item, method: :delete %></td>
</tr>
<% end %>
<% end %> 
<% else %>
NO BUGS YET
<% end %>  
</table>

app/views/bgs/new.html.erb
<h5>Project Name :<%= @pj.pname %>(<%= link_to "back",new_pj_path %>)</h5> 
<%= render 'form' %><br/>
<h4 align="center"><caption>List Of Bugs For This Project</caption></h4>
<table class="table table-hover">
       <% if @pj.bgs.exists? %>
    <tr>
    <th>Bug Name</th>
    <th>Priority</th>
    <th>Created On</th>
    <th>Last Update</th>
    <th> </th>
     
  </tr>
<% for item in @pj.bgs %>
<% if !item.bname.nil? %>
<tr>
  <td><%= item.bname %></td>
  <td> <%= item.priority %></td>
  <td><%= item.created_at.strftime("%b %d, %Y") %></td>
  <td><%= item.updated_at.strftime("%b %d, %Y") %></td>
  <td><%= link_to 'Show', item %> 
   <%= link_to 'Edit', edit_bg_path(item) %> 
     <%= link_to 'destroy', item,:class => "btn btn-mini btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
<% end %> 
<% else %>
NO BUGS YET
<% end %>  
</table> 

app/views/bgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bg.bname %>
</p>

<p>
  <b>priority:</b>
  <%= @bg.priority %>
</p>


<%= link_to 'Edit', edit_bg_path(@bg) %> |
<%= link_to 'Back', bgs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nestedfrom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pjs/new.html.erb
<div class="alert alert-error">
  <h4 class="pagination-centered">Enter New Project Information</h4>
</div>
 <%= simple_form_for @pj do |f| %>
 <%= f.input :pname, :label => "Project Name :"  %>
 <%= f.label "Choose Client :" %>
 <%= f.input :user_id %><br />
 <%= f.button :submit, 'Save', :class => 'btn btn-huge btn-info btn-embossed mlm' %>

 <% end %>
<hr />
<h4><u>List of all Projects</u></h4>
 
<% if !@pjs.blank? %>
<% for item in @pjs %>
<%= link_to item.pname, :controller => :bgs, :action => :new, :id => item.id %> <br />
<% end %>
<% else %>
No Projects yet
<% end %>